### ISSUE TITLE
python-use-type-annotations

### ISSUE THREAD

**Issue by karl0ss** [pre-commit/pygrep-hooks#118]
Hope you can help, I have configured pre-commit and this is my `.pre-commit-config.yaml`

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2500]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --branch, adf_release]
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
        args: [--style "google"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length, "180"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--docstring-convention, google]
        additional_dependencies: [flake8-bugbear, flake8-docstrings]
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        files: src/
```

All my other hooks seem to be fine, but I have funtions in my code at the moment without types, e.g.

```
def get_base_name(file):
    """Returns file basename from file path.

    Args:
        file (): File path

    Returns:
        [str]:File basename
    """
    return os.path.basename(file)
```

And these do not seem to be getting picked up by the hook? When I run pre-commit with --verbose I get (commented out the other hooks for this output)

```
pre-commit run --all-files --verbose
type annotations not comments............................................Passed
- hook id: python-use-type-annotations
- duration: 0.2s
```

So the hook seems to run, but doesn't appear to have checked/run on anythiing.

Hope you have an idea.

Thanks

Karl
