### ISSUE TITLE
.rst: Auto-Fix Option?

### ISSUE THREAD

**Issue by ax3l** [pre-commit/pygrep-hooks#92]
Hi,

since the detection for the groups:
```yaml
- id: rst-backticks
- id: rst-directive-colons
- id: rst-inline-touching-normal
```
is really precise, is it possible to add an option to auto-fix the found locations? :)
